version: 2

registries:
  morphe-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/MorpheApp/morphe-patcher
    username: nvbangg
    password: ${{ secrets.PAT_TOKEN }}

updates:
  - package-ecosystem: "gradle"
    directory: "/scripts/bundle-parser"
    schedule:
      interval: "weekly"
    registries:
      - morphe-packages
    allow:
      - dependency-name: "app.morphe:*"
    cooldown:
      exclude:
        - "app.morphe:*"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
