contact_links:
  - name: Patch Explorer Issues
    url: https://github.com/Paresh-Maheshwari/patch-explorer/issues
    about: Submit issues related to Patch Explorer in Paresh Maheshwari's repository.