contact_links:
  - name: Submit Patch Bundle
    url: https://github.com/Jman-Github/ReVanced-Patch-Bundles/issues
    about: Please submit your patch bundles to the Jman-Github/ReVanced-Patch-Bundles repository